### ISSUE TITLE
Error thrown when ServerPackages folder is non existent 

### ISSUE THREAD

**Issue by Entelogical** [Barocena/wally-patch-package#1]
When I run `wally-patch-package` the following error is thrown:

```
node:fs:1515
  const result = binding.readdir(
                         ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\PATH\ServerPackages\_Index'
    at Object.readdirSync (node:fs:1515:26)
    at Object.readdirSync (pkg/prelude/bootstrap.js:1306:35)
    at C:\snapshot\build\app.js:19373:34
    at Array.forEach (<anonymous>)
    at fetchPackageInfo (C:\snapshot\build\app.js:19370:23)
    at applyPatch (C:\snapshot\build\app.js:23524:21)
    at _Command.<anonymous> (C:\snapshot\build\app.js:23582:5)
    at _Command.listener [as _actionHandler] (C:\snapshot\build\app.js:1381:21)
    at C:\snapshot\build\app.js:2050:69
    at _Command._chainOrCall (C:\snapshot\build\app.js:1964:16) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'C:\\Users\\PATH\\ServerPackages\\_Index'
}
```

**Comment by Barocena** [comment]
Thanks for the heads up, solved in v1.2.1 👌🏼
